#!/bin/bash
if  [ -e /usr/local/bin/virtualenvwrapper.sh ]; then
    source /usr/local/bin/virtualenvwrapper.sh
elif [ -e /usr/bin/virtualenvwrapper.sh ]; then
    source /usr/bin/virtualenvwrapper.sh
else
    source /etc/bash_completion.d/virtualenvwrapper
fi

for env in $(workon | grep '^coffee-[0-9]\.[0-9]'); do
    rmvirtualenv $env
done

for v in 2.6 2.7 3.1 3.2 3.3; do
    mkvirtualenv coffee-$v -p $(which python$v)
    pushd ~/Documents/PyExecJS
        ~/.virtualenvs/coffee-$v/bin/python setup.py develop
    popd
done
